### ISSUE TITLE
Use immutable parsing options

### ISSUE THREAD

**Issue by kostiakoval** [3lvis/JSON#1]
Mutability is bad, it caused an error. `[mutableCopy]` does shallow coping, so I would prefer to use immutable type in json.

```
 id result = [NSJSONSerialization JSONObjectWithData:data
                                                options:0
                                                  error:&error];
```

**Comment by 3lvis** [comment]
I thought `option: 0` is the current used one

``` objc
enum {
   NSJSONReadingMutableContainers = (1UL << 0),
   NSJSONReadingMutableLeaves = (1UL << 1),
   NSJSONReadingAllowFragments = (1UL << 2)
};
typedef NSUInteger NSJSONReadingOptions;
```

https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSJSONSerialization_Class/index.html#//apple_ref/c/tdef/NSJSONReadingOptions

**Comment by 3lvis** [comment]
@kostiakoval using `0` means that all the leaves are immutable, have you checked?

**Comment by kostiakoval** [comment]
@3lvis  yes I've checked it with o they are immutable, I will make a RP to hyper fork.
(1UL << 0) == 1
(0UL << 0) == 0

**Comment by 3lvis** [comment]
I can change it :)

**Comment by 3lvis** [comment]
Fixed on https://github.com/3lvis/JSON/releases/tag/2.1.1
